# Generated by Django 5.0.6 on 2024-05-27 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_guidetmcompany_alter_vehicle_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CC_breakdown_date', models.DateField()),
                ('CC_operating_hours', models.FloatField(max_length=64)),
                ('CC_breakdown_description', models.TextField()),
                ('CC_spares_list', models.TextField()),
                ('CC_recovery_date', models.DateField()),
                ('CC_vehicle_downtime', models.IntegerField()),
                ('CC_breakdown_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.guidebreakdownunit')),
                ('CC_repair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.guiderepairtype')),
                ('CC_service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CC_service_company', to='mainApp.vehicle')),
                ('CC_vehicle_SN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CC_vehicle_SN', to='mainApp.vehicle')),
            ],
        ),
    ]
