# Generated by Django 5.0.6 on 2024-05-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_clientclaim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuideServiceCompany',
        ),
    ]
