# Generated by Django 5.0.6 on 2024-05-29 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_silantclient_alter_vehicle_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientclaim',
            name='CC_service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.silantservicecompany'),
        ),
        migrations.AlterField(
            model_name='clientclaim',
            name='CC_vehicle_SN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.vehicle'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='TM_service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.silantservicecompany'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='TM_vehicle_SN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.vehicle'),
        ),
    ]
