# Generated by Django 5.0.6 on 2024-06-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_clientclaim_cc_service_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientclaim',
            name='CC_recovery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientclaim',
            name='CC_vehicle_downtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
